### ISSUE TITLE
Boshqalar ko'rmasligi kerak bo'lgan narsalarni .env faylda saqlash kerak. Ayniqsa API linkni .env faylda saqlash shart

### ISSUE THREAD

**Issue by khaitbek** [FakhriddinovSh/farobiyuz#2]
![image](https://user-images.githubusercontent.com/69072537/232858264-9f978436-1cfe-4035-a92b-11c4a91bf553.png)

**Comment by MuhammadAkbar-Ramazonov** [comment]
Assalomu aleykum xop bo’ladi  Xayitbek albatta to’g’irlab qo’yamiz, raxmat kattakon )

**Comment by FakhriddinovSh** [comment]
.env added and project secured. Thanks bro )
